version: '{build}'
install:
  - ps: Invoke-WebRequest http://kitcreator.rkeene.org/kits/73e51976aa01502eb5b4365a35ac35ad38f46414/tclkit.exe -OutFile tclkit.exe
  - ps: Invoke-WebRequest https://ci.appveyor.com/api/buildjobs/087d5bjjeu9b1v30/artifacts/jimsh.exe -OutFile jimsh.exe
  - ps: Invoke-WebRequest https://sqlite.org/2017/sqlite-tools-win32-x86-3210000.zip -OutFile sqlite-tools.zip
build_script:
  - cmd: assemble.cmd /tclsh:tclkit.exe
  - cmd: 7z e sqlite-tools.zip
test_script:
  - cmd: tclkit.exe tests.tcl
