# -*- mode: ruby -*-
# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.provision :shell, path: "bootstrap.sh", run: "always"
  config.vm.synced_folder "..", "/sqawk"

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "192"]
    # vb.customize ["modifyvm", :id, "--cpuexecutioncap", "80"]
  end

  config.vm.define "sqawkdev" do |sqawkdev|
    sqawkdev.vm.box = "ubuntu/trusty64"
  end
end
