name: CI
on: [push, pull_request]
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get install -y tcl tcllib libsqlite3-tcl
      - name: Run tests
        run: |
          make test
  
  mac:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          brew install tcl-tk
      - name: Run tests
        run: |
          make test
  
  windows:
    runs-on: windows-latest
    steps:
      - name: 'Disable `autocrlf` in Git'
        run: git config --global core.autocrlf false
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download dependencies
        run: |
          Invoke-WebRequest http://kitcreator.rkeene.org/kits/ae78c6ebb1cca64104a326db1be0110e8b2457c9/tclkit.exe -OutFile tclkit.exe
          Invoke-WebRequest https://dbohdan.com/dist/jimsh-0.80-win32.7z -OutFile jimsh.7z
          Invoke-WebRequest https://sqlite.org/2017/sqlite-tools-win32-x86-3210000.zip -OutFile sqlite-tools.zip
          7z e jimsh.7z
          7z e sqlite-tools.zip
      - name: Run tests
        run: |
          .\assemble.cmd /tclsh:tclkit.exe
          .\tclkit.exe tests.tcl
